name: Feature Request
description: Suggest a new feature, functionality, or improvement.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please check the existing `ISSUES` to ensure you are not suggesting something that has already been proposed. If you find a similar issue, please contribute additional information if necessary.
  - type: textarea
    attributes:
      label: Description
      description: What would you like to improve? Please describe your suggestion and what need you currently have that this suggestion would solve.
      placeholder: |
        I think the page ... would be better if ... because I had difficulty in...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation suggestion
      description: Have you thought about how this could be implemented? Share images, code, or references that you consider helpful for implementing this suggestion.
      placeholder: |
        We could change ... to add ... Here are some drawings of how this could look:
        ![image](https://example.com/image)
